{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <hogwarts.test_allure_feature_story_demo1.TestLogin object at 0x10c3f8790>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_feature_story_demo1.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1655432378541, "stop": 1655432378541}, {"name": "点击密码", "status": "passed", "start": 1655432378541, "stop": 1655432378541}, {"name": "点击登录后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"/Users/zxmac/Desktop/workspace/project/hogwarts/test_allure_feature_story_demo1.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1655432378541, "stop": 1655432378541}], "attachments": [{"name": "stdout", "source": "950c839f-edd2-46f4-a03f-d57f14d2f7a3-attachment.txt", "type": "text/plain"}], "start": 1655432378541, "stop": 1655432378542, "uuid": "103f685a-ab93-4d8c-a076-ce69b972a8ff", "historyId": "6d16477e0e36f1da1403ccd08ba7e244", "testCaseId": "1cd18ebe077b9c296a343b820cd8f237", "fullName": "test_allure_feature_story_demo1.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure_feature_story_demo1"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro-6.local"}, {"name": "thread", "value": "28421-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_feature_story_demo1"}]}